name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install libwebkit2gtk-4.0-dev
        sudo apt-get install build-essential libgtk-3-dev
        sudo apt-get install libappindicator3-dev
        go install github.com/wailsapp/wails/v2/cmd/wails@latest
        yarn

    - name: Build Wails for macOS, Windows, Linux
      run: |
        wails build -platform darwin/amd64 -o ./build/nyotepad-mac
        wails build -platform windows/amd64 -o ./build/nyotepad-win
        wails build -platform linux/amd64 -o ./build/nyotepad-linux

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

    - name: Upload Release Asset - Mac
      id: upload-release-asset-mac
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./build/nyotepad-mac
        asset_name: nyotepad-mac
        asset_content_type: application/octet-stream

    - name: Upload Release Asset - Windows
      id: upload-release-asset-win
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./build/nyotepad-win
        asset_name: nyotepad-win
        asset_content_type: application/octet-stream

    - name: Upload Release Asset - Linux
      id: upload-release-asset-linux
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./build/nyotepad-linux
        asset_name: nyotepad-linux
        asset_content_type: application/octet-stream
